### PR TITLE
remove select case

### PR DESCRIPTION
**Pull request by codermarcel**
pow pow

### CODE REVIEW

**Comment by paragonie-scott** [comment]
Is there any specific reason why you prefer `pow()` to a select case?

**Comment by LavaToaster** [comment]
Non-finite length?

**Comment by paragonie-scott** [comment]
Check out RFC 6238. They limit values to 2^31 - 1.

https://tools.ietf.org/html/rfc6238#page-13

**Comment by LavaToaster** [comment]
That's a reference implementation of the spec, which uses the int type which is constrained to a 32 bit integer value of 2^31 - 1. I can't see wording in the spec to limit the length of the value.

**Comment by paragonie-scott** [comment]
There are two limitations provided:
1. The offset between 0 and 15 puts a maximum of 4 bytes (due to SHA1 output length) -- 32 bits.
   - ceil(log(2^32, 10)) is 10.
2. If you use a different value for the upper byte, the test vectors will not pass.

**Comment by LavaToaster** [comment]
Ah, ok. To be honest then, It's just cleaner.

Have you looked into [this](https://github.com/Spomky-Labs/otphp) package?

**Comment by codermarcel** [comment]
@paragonie-scott 
Well, I think it is cleaner and simpler than the select case (don't you agree?)

I didn't think of any limitations for $length though, so you might want to enforce those minimum and maximum lengths.

**Comment by paragonie-scott** [comment]
It's certainly more succinct.

I didn't think it's cleaner under the hood because I believed (at the time I first wrote this) `pow()` returns a float. Int -> float -> int is unclean.

But since this isn't a concern, I'll just use `**` instead. (This library will never be backported for PHP 5 by Paragon, so I can get away with this.)

Thanks for the contribution. :)

**Pull request merged**
